# role: ethpandaops.general.ethereum_node
ethereum_node_el: geth

# role: ethpandaops.general.geth
geth_container_image: "client-go"
geth_container_env:
  VIRTUAL_HOST: "examplehost"
  VIRTUAL_PORT: "3000"
  LETSENCRYPT_HOST: "letsencrypt_host"
geth_container_command_extra_args:
  - --http.api=eth,net,web3,debug
  - --http.vhosts=*
  - --networkid={{ ethereum_network_id }}
  - --syncmode=full
  - --bootnodes={{ ethereum_el_bootnodes | join(',') }}
  - --ethstats={{ inventory_hostname }}:{{ ethstats_secret }}@{{ ethstats_url }}
geth_init_custom_network: true
geth_init_custom_network_genesis_file: "{{ eth_testnet_config_dir }}/genesis.json"
