- hosts: all
  serial: "{{ batch_count | default('100%') }}"
  become: true
  roles:
    - role: robertdebock.fail2ban
      tags: [init-server, fail2ban]
    - role: geerlingguy.docker
      tags: [init-server, docker]
    - role: geerlingguy.pip
      pip_install_packages:
        - name: docker
        - name: docker-compose
      tags: [init-server, pip]
    - role: ethpandaops.general.docker_cleanup
      tags: [init-server, docker_cleanup]
    - role: ethpandaops.general.docker_network
      tags: [init-server, docker_network]
    - role: ethpandaops.general.node_exporter
      tags: [init-server, node_exporter]
    - role: ethpandaops.general.prometheus
      tags: [init-server, prometheus]

- hosts: all 
  serial: "{{ batch_count | default('100%') }}"
  become: true
  roles:
    - role: eth_testnet_config
      tags: [ethereum, eth_testnet_config]
      vars:
        eth_testnet_config_local_dir_enabled: true
        eth_testnet_config_local_dir_src: output/custom_config_data
    - role: validator_keys
      when: ethereum_node_cl_validator_enabled == true
      tags: [ethereum, validator_keys]
    - role: ethpandaops.general.ethereum_node
      tags: [ethereum, ethereum_node]
      vars:
        ethereum_node_el: geth
        geth_init_custom_network: true
  post_tasks:
    - name: Wait between runs
      tags: [ethereum, ethereum_node]
      ansible.builtin.pause:
        seconds: >-
          {{
            batch_count is defined | ternary(
                (batch_wait_seconds | default(30)),
                0
              )
          }}
